/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class BaseResponse, NSString, SKBuiltinBuffer_t;

@interface HongBaoRes : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* errorMsg;
@property(assign, nonatomic) int errorType;
@property(assign, nonatomic) int cgiCmdid;
@property(retain, nonatomic) NSString* platMsg;
@property(assign, nonatomic) int platRet;
@property(retain, nonatomic) SKBuiltinBuffer_t* retText;
@property(retain, nonatomic) id baseResponse;
+(void)initialize;
@end

@interface NSString (NSString_SBJSON)
-(id)JSONDictionary;
-(id)JSONArray;
-(id)JSONValue;
@end

