/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "WeChat-Structs.h"
//#import "NSCopying.h"

@class NSObject, NSString, NSData, WXPBGeneratedMessage;

@interface ProtobufCGIWrap : NSObject  {}

@property(assign, nonatomic) int m_netwrokStrategy;
@property(assign, nonatomic) double m_douTimeout;
@property(assign, nonatomic) unsigned long m_uiRetryCount;
@property(assign, nonatomic) BOOL m_bNotifyPartLen;
//@property(retain, nonatomic) UrlInfo* m_oUrlInfo;
@property(retain, nonatomic) NSObject* m_oUserData;
@property(assign, nonatomic) Class m_eventHandlerClass;
@property(assign, nonatomic) unsigned long m_uiMessage;
@property(retain, nonatomic) NSData* m_dtResponseDecryptKey;
@property(assign, nonatomic) unsigned long m_uiRequestEncryptType;
@property(retain, nonatomic) NSString* m_nsUri;
@property(retain, nonatomic) NSString* m_nsCgiName;
@property(assign, nonatomic) unsigned long m_uiScene;
@property(assign, nonatomic) unsigned long m_uiCgi;
@property(assign, nonatomic) unsigned long m_uiChannelType;
@property(retain, nonatomic) WXPBGeneratedMessage* m_pbResponse;
@property(assign, nonatomic) Class m_pbRespClass;
@property(retain, nonatomic) WXPBGeneratedMessage* m_pbRequest;
-(id)init;
@end

