/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */


@interface WXPBGeneratedMessage : NSObject {
	int _has_bits_[3];
	int _serializedSize;
//	PBClassInfo* _classInfo;
	id* _ivarValueDict;
}
@property(readonly, assign) int serializedSize;
+(id)parseFromData:(id)data;
-(BOOL)hasProperty:(int)property;
-(unsigned long)continueFlag;
-(id)baseResponse;
-(void)setBaseRequest:(id)request;
-(void)writeValueToCodedOutputStreamNoTag:(id)codedOutputStreamNoTag value:(id)value fieldType:(unsigned char)type;
-(void)writeValueToCodedOutputStream:(id)codedOutputStream value:(id)value fieldNumber:(int)number fieldType:(unsigned char)type;
-(void)writeToCodedOutputStream:(id)codedOutputStream;
-(int)computeValueSizeNoTag:(id)tag fieldType:(unsigned char)type;
-(int)computeValueSize:(id)size fieldNumber:(int)number fieldType:(unsigned char)type;
-(id)serializedData;
-(BOOL)isInitialized;
-(BOOL)isMessageInitialized:(id)initialized;
-(id)readValueFromCodedInputStream:(id)codedInputStream fieldType:(unsigned char)type;
-(id)mergeFromCodedInputStream:(id)codedInputStream;
-(id)mergeFromData:(id)data;
-(id)valueAtIndex:(int)index;
-(void)setValue:(id)value atIndex:(int)index;
-(int)indexOfPropertyWithSetter:(const char*)setter;
-(int)indexOfPropertyWithGetter:(const char*)getter;

@end

